services:
  mysql:
    image: "mysql:9.2"
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  valkey:
    image: "valkey/valkey:8.0-alpine"
    ports:
      - "127.0.0.1:6379:6379"
