default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
  connect_timeout: 10

development:
  <<: *default
  database: tumblr_archiver_development

